### ISSUE TITLE
ReRun formatter runs all testcases after 4.2.2 release

### ISSUE THREAD

**Issue by abhishek8908** [cucumber/cucumber-jvm#1565] opened 2019-02-22 12:57 UTC
## Summary

ReRun runnner runs all testcases after 4.2.2 release

## Expected Behavior
ReRun runner should only rerun failed testcases.

## Current Behavior

ReRun test runner runs every testcase. This problem exists after 4.2.2

Parse rerun file in RuntimeOptions #1529

## Steps to Reproduce (for bugs)
Create a Testng runner to create a rerun output file

```
@CucumberOptions(plugin = { "json:target/cucumber-parallel/cucumber-report.json", "html:target", "rerun:target/failed_scenarios.feature"}
        , extraGlue = {"com.xxx.base.cucumber"}
        , monochrome = true
        , strict = true)

public class HTFCucumberBaseTests extends AbstractTestNGCucumberTests {

    @Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}
```
Create a Testng runner to re run the failed testcases.
```
@CucumberOptions(plugin = { "json:target/cucumber-parallel/cucumber-rerun-report.json", "html:target/feature-rerun"}
        , features = "@target/failed_scenarios.feature"
        , extraGlue = {"com.xxxx.base.cucumber"}
        , monochrome = true
        , strict = true)

public class CucumberReRunTests extends AbstractTestNGCucumberTests {

}

```

 

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mpkorstanje** [comment] 2019-02-22 20:14
I can't reproduce this behavior. 

1) Can you include a sample of the rerun file? 
2) Can you ensure that all Cucumber dependencies are up to date and on your class path?

**Comment by abhishek8908** [comment] 2019-02-23 19:24
@mpkorstanje 
This is the data in my rerun file.
src\test\features\acq\cvb\Transactions.feature:26:27

also I am using windows OS

**Comment by mpkorstanje** [comment] 2019-02-23 19:51
This was fixed in 4.2.3.

https://github.com/cucumber/cucumber-jvm/issues/1547

**Comment by abhishek8908** [comment] 2019-02-23 20:29
@mpkorstanje
 Yes correct ,still surprised to see it in 4.2.3 .
I just checked all my dependencies are correct.(4.2.3)

I am on win 10

**Comment by mpkorstanje** [comment] 2019-02-23 21:06
So can you provide an MCVE? Preferably in the form of a github repo?


https://stackoverflow.com/help/mcve

**Comment by mpkorstanje** [comment] 2019-03-08 12:19
@abhishek8908 if you are able to reproduce this problem as an MCVE please feel free to reopen this issue.

**Closed by mpkorstanje** 2019-03-08 12:19 UTC
Labels: Bug, Core, Need More Info

**Comment by abhishek8908** [comment] 2019-03-08 12:30
@mpkorstanje this issue is not reproducible in version 4.2.5+
