### ISSUE TITLE
ConstantPoolTypeIntrospector.java:37 problem with Oracle JDK 8u60+ 

### ISSUE THREAD

**Issue by bencody** [cucumber/cucumber-jvm#949] opened 2016-01-18 08:55 UTC
I'm using Cucumber 1.2.4 with the Java 8 extension. Everything worked fine with Oracle's JDK 8u45. After upgrading to JDK 8u60, Cucumber is throwing an exception:

```java
java.lang.IllegalArgumentException: Wrong type at constant pool index
        at sun.reflect.ConstantPool.getMemberRefInfoAt0(Native Method)
        at sun.reflect.ConstantPool.getMemberRefInfoAt(ConstantPool.java:47)
        at cucumber.runtime.java8.ConstantPoolTypeIntrospector.getTypeString(ConstantPoolTypeIntrospector.java:37)
        at cucumber.runtime.java8.ConstantPoolTypeIntrospector.getGenericTypes(ConstantPoolTypeIntrospector.java:27)
        at cucumber.runtime.java.Java8StepDefinition.&lt;init&gt;(Java8StepDefinition.java:45)
        at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:162)
        ... 74 more
```

The newest JDK version (8u66) unfortunately also has this issue.

**Comment by aslakhellesoy** [comment] 2016-01-18 08:57
Dupe of #912

**Closed by aslakhellesoy** 2016-01-18 08:57 UTC
