### ISSUE TITLE
When using 'cucumber-junit-platform-engine' rerun files are not supported. How to rerun failed cases ?

### ISSUE THREAD

**Issue by gorakshasabnis** [cucumber/cucumber-jvm#2843] opened 2024-01-05 13:53 UTC
In JUnit 4 failure cases were captured using 'rerun' like below:

```
@RunWith(Cucumber.class)
@CucumberOptions(
        plugin = {"pretty", "rerun:target/failed-scenarios/FailedCases.txt"},
        features = "src/test/resources/features"
)
public class TestRunner {}
```

Which can be run using below Junit4 runner
```

@RunWith(Cucumber.class)
@CucumberOptions(
            plugin = {"pretty"},
            features = "@target/failed-scenarios/FailedCases.txt"
)
public class TestReRunner {}
```

Q: However in JUnit5, 'FailedCases.txt' gets generated by mentioning rerun in 'PLUGIN_PROPERTY_NAME'. File gets generated too, but there is no way to execute that file.

Can someone please guide for re-running failed cases using Cucumber JUnit5 ?

**Comment by mpkorstanje** [comment] 2024-01-05 14:00
Duplicate of https://github.com/cucumber/cucumber-jvm/issues/2805

**Closed by mpkorstanje** 2024-01-05 14:00 UTC

**Comment by gorakshasabnis** [comment] 2024-01-05 14:18
@mpkorstanje is there is any different documention on how exactly to run this class along with '@ suite' ?

**Comment by mpkorstanje** [comment] 2024-01-05 15:06
For Maven you could use the exec Maven plugin and bind it to the test phase.

https://www.mojohaus.org/exec-maven-plugin/
