### ISSUE TITLE
Error running Background for Scenario Outlines defined after Scenarios

### ISSUE THREAD

**Issue by jaybrad111** [cucumber/cucumber-jvm#827] opened 2015-01-16 02:24 UTC
Since updating my project's cucumber-jvm version from 1.1.1 to 1.2.2, I've had problems executing the background steps before Scenario Outlines when I run all scenarios in a feature file. I found a nearly identical cucumber issue [here](https://github.com/cucumber/cucumber/issues/560). This issue comes up in 1.2.0 as well.

Consider the following as a feature file with a Background, Scenario, and Scenario Outline.

```
Feature:
  As a user I want...

Background:
  Given the following things exist
    | thing name |
    | thing |
  And wait for the homepage to load

Scenario: Scenario
  Given I am on the homepage
  And I do something first

Scenario Outline: Scenario Outline
  Given I am on the homepage
  And I do <something> second
    Examples:
      | something |
      | thing |
```

In this case we get the following errors after the Cuke run:
_Expected step: "Given I am on the homepage" got step: "Given the following things exist"_
_Expected step: "And I do thing second" got step: "Given the following things exist"_
-  When I run all the scenarios here in a feature file, the background is executed for "Scenario", but not for "Scenario Outline"
- "Scenario Outline" fails at "Given I am on the homepage"
- If Scenario and Scenario Outline are swapped, there is no issue
  - I've confirmed that multiple Scenarios (not Scenario Outlines) can follow one Scenario Outline that comes first in the file, and the problem does not occur either, which strikes me as very strange

Is this a bug or a limitation that I'll have to work around?

**Comment by brasmusson** [comment] 2015-03-08 19:02
@jaybrad111 I cannot reproduce this issue. When I copy the feature described in the issue I get no errors. Moreover, in the java-calculator example (https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-calculator/src/test/resources/cucumber/examples/java/calculator/basic_arithmetic.feature) a feature with similar structure: 
```
  Background:
  Scenario:
  Scenario:
  Scenario Outline:
```
has been and is successfully executed in each build (in the openjkd7 job on [Travis](https://travis-ci.org/cucumber/cucumber-jvm/))

If you still have this problem, it would be really helpful if you could create a feature with this problem in for instance the calculator-java example, and supply it in a pull request. A failing build on Travis would simplify the investigation of the issue.

**Comment by vveliev** [comment] 2015-08-05 14:11
similar issue for cucumber (2.0.2)

**Comment by lunivore** [comment] 2017-06-27 17:23
Hi @vveliev, If this is still important to you, please provide some code to reproduce the problem or let us know that you're doing so. We haven't been able to reproduce the problem on our side. If we don't hear back from you, we'll close this ticket in a week. Thanks!

**Closed** 2017-07-09 18:57 UTC

**Comment by Prasannajnaeyulu** [comment] 2017-12-21 09:44
I too faced the same issue. But it's with the serenity reporter I am getting NPE. This is happening if **Scenario Outline**  was at the last in a feature file. If it's at the beginning then all scenarios are executing without any issues as @jaybrad111 pointed out.

Feature: Areas  Time elapsed: 22.407 sec  <<< ERROR!
java.lang.NullPointerException: null
        at cucumber.runtime.formatter.SerenityReporter.startExample(SerenityReporter.java:575)                                                                                                    at cucumber.runtime.formatter.SerenityReporter.handleTestCaseStarted(SerenityReporter.java:245)                                                                                           at cucumber.runtime.formatter.SerenityReporter.lambda$new$1(SerenityReporter.java:130)
        at cucumber.runner.EventBus.send(EventBus.java:28)
        at cucumber.api.TestCase.run(TestCase.java:55)                                               at cucumber.runner.Runner.runPickle(Runner.java:80)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)                      at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)                      at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)                          at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)                                    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:108)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)                                 at org.junit.runners.Suite.runChild(Suite.java:127)
        at org.junit.runners.Suite.runChild(Suite.java:26)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)                         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)                           at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:107)                                                                                    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:88)                                                                                             at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:57)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)                                                                                   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)                                                                                                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by brasmusson** [comment] 2017-12-21 11:29
The SerenityReporter is not part of Cucumber-JVM, you should raise an issue with whoever developed the SerenityReporter.
