### ISSUE TITLE
Pico container lifecycle changes

### ISSUE THREAD

**Issue by mszalbach** [cucumber/cucumber-jvm#2771] opened 2023-06-26 09:39 UTC
### 👓 What did you see?

The Pico container lifecylce changed between 7.11.2 and 7.12.1 because of this issue #2724

The dispose method is not called after each Scenario like before, but only once after the first scenario. In the following runs the state is not started anymore and the dispose method is not called anymore. Also affects the start and stop methods.

@After works like before.

### ✅ What did you expect to see?

The same behavior like in 7.11.2 or a hint that there was a breaking change and disposable should not be used anymore.

### 📦 Which tool/library version are you using?

Java, cucumber-bom:7.12.1

### 🔬 How could we reproduce it?

See example project https://github.com/mszalbach/CucumberDisposable

Readme shows the difference state outputs when running with different versions.

Run with ./mvnw test

**Comment by mpkorstanje** [comment] 2023-06-27 09:35
@jkronegg I think it's worth reverting #2725 now.

**Comment by jkronegg** [comment] 2023-06-27 10:52
@mszalbach sorry for the issue.  The code repository https://github.com/mszalbach/CucumberDisposable gives me a 404 not found. Can you make the project visible or correct the URL ?

**Comment by mszalbach** [comment] 2023-06-27 14:11
@jkronegg Sorry I thought the repo was already public. That should be fixed now.

**Comment by jkronegg** [comment] 2023-06-29 05:30
> @jkronegg I think it's worth reverting #2725 now.

As the issue is fixed by #2772, I don't see any advantage to revert #2725. With the original code, the test harness was insufficient: lifecycle events were tested only on the first test scenario, not when using multiple test scenarios.

**Closed** 2023-07-02 18:08 UTC

**Comment by jkronegg** [comment] 2023-07-02 20:49
@mszalbach thanks for the detailed bug report. This should be corrected with the fresh new Cucumber [v7.13.0](https://github.com/cucumber/cucumber-jvm/releases/tag/v7.13.0). Please excuse me for the wasted time.

**Comment by mszalbach** [comment] 2023-07-03 07:12
Thanks a lot. I am looking forward to use this as soon as the release hits Maven central.

**Comment by mpkorstanje** [comment] 2023-07-03 07:28
That maybe take a minute. The key expired. https://github.com/cucumber/cucumber-jvm/actions/runs/5437899604/jobs/9888762794

**Comment by mszalbach** [comment] 2023-07-07 10:43
Thanks. Release works and my job is back in the green.
