### ISSUE TITLE
AmbiguousStepDefinitionsException with different gluecode

### ISSUE THREAD

**Issue by iyiConsultancy** [cucumber/cucumber-jvm#1278] opened 2017-11-15 07:54 UTC
Hi,

I have 2 different gluecode's but I got the exception of AmbiguousStep.

Steps
1) I change the gherkin code " I fill <advertentieDatum> date of advertentie" to
"I fill the current date of advertentie". 
2) I copy paste the gluecode and edit this to the second one below.
3) I runned the test and I received an exception.

@Given("^I fill (.+) date of advertentie$")
	public void i_fill_date_of_advertentie(String advertentieDate) throws Throwable {
		advertentiePage.advertentieDate(advertentieDate);
	}

@Given("^I fill the current date of advertentie$")
	public void current_date_of_advertentie() throws Throwable {
		advertentiePage.advertentieDateCurrentDate();
	}

**Comment by mlvandijk** [comment] 2017-11-15 08:31
Hello @iyiConsultancy ,

The AmbiguousStep exception means that you have two step definitions where Cucumber cannot determine which step to use. 

"I fill the current date of advertentie" matches both 
@given("^I fill the current date of advertentie$") and
@given("^I fill (.+) date of advertentie$")
and Cucumber doesn't know which to use

You could solve this by using something like this:

@given("^I fill (.+) date of advertentie$")
public void i_fill_date_of_advertentie(String advertentieDate) throws Throwable {
  if (advertentieDate.equals("current") {
    advertentiePage.advertentieDateCurrentDate();
  }
  advertentiePage.advertentieDate(advertentieDate);
}


As this is a question, not a bug/feature request, I am closing this issue.
For question, please contact the community via one of the [support options](https://cucumber.io/support).

**Closed by mlvandijk** 2017-11-15 08:31 UTC
