### ISSUE TITLE
Run Test cucumber-android 1.1.8 - java.io.IOException

### ISSUE THREAD

**Issue by chiavegatto** [cucumber/cucumber-jvm#775] opened 2014-09-14 05:09 UTC
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for br.com.calcdesempenho:CalcDesempenho-Test:apk:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 130, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                     : C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\unpacked-libs\bcc_calc-desempenho\classes.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building CalcDesempenho-Test 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- android-maven-plugin:3.9.0-rc.1:generate-sources (default-generate-sources) @ CalcDesempenho-Test ---
[INFO] Manifest copying disabled. Using default manifest only
[INFO] Extracting libs
[INFO] Extracting apklib cucumber-android...
[INFO] Manifest merging disabled. Using project manifest only
[INFO] Generating R file for br.com.calcdesempenho:CalcDesempenho-Test:apk:1.0
[INFO] Generating R file for apklibrary: info.cukes:cucumber-android
[INFO] Adding R gen folder to compile classpath: C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\generated-sources\r
[WARNING] Adding AIDL gen folder to compile classpath: C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\generated-sources\aidl
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ CalcDesempenho-Test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\src\main\resources
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ CalcDesempenho-Test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\classes
[INFO] 
[INFO] --- android-maven-plugin:3.9.0-rc.1:proguard (default-proguard) @ CalcDesempenho-Test ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ CalcDesempenho-Test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ CalcDesempenho-Test ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ CalcDesempenho-Test ---
[INFO] 
[INFO] --- android-maven-plugin:3.9.0-rc.1:emma (default-emma) @ CalcDesempenho-Test ---
[INFO] 
[INFO] --- android-maven-plugin:3.9.0-rc.1:dex (default-dex) @ CalcDesempenho-Test ---
[INFO] Convert classes to Dex : C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\classes.dex
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ CalcDesempenho-Test ---
[INFO] Building jar: C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\CalcDesempenho-Test-1.0.jar
[INFO] 
[INFO] --- android-maven-plugin:3.9.0-rc.1:apk (default-apk) @ CalcDesempenho-Test ---
[INFO] Generating debug apk.
[INFO] Creating debug key signed apk file C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\CalcDesempenho-Test-1.0.apk
[INFO] Creating additional unsigned apk file C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\CalcDesempenho-Test-1.0-unsigned.apk
[INFO] 
[INFO] --- android-maven-plugin:3.9.0-rc.1:internal-pre-integration-test (default-internal-pre-integration-test) @ CalcDesempenho-Test ---
[INFO] C:\Desenvolvimento\android-sdk\build-tools\19.0.0\aapt.exe [dump, xmltree, C:\Users\Rafael\.m2\repository\br\com\calcdesempenho\calc-desempenho\0.0.1-SNAPSHOT\calc-desempenho-0.0.1-SNAPSHOT.apk, AndroidManifest.xml]
[INFO] Waiting for initial device list from the Android Debug Bridge
[INFO] android.devices parameter not set, using all attached devices
[INFO] Device 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 found.
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :   Successfully uninstalled br.com.calcdesempenho
[INFO] C:\Desenvolvimento\android-sdk\build-tools\19.0.0\aapt.exe [dump, xmltree, C:\Users\Rafael\.m2\repository\br\com\calcdesempenho\calc-desempenho\0.0.1-SNAPSHOT\calc-desempenho-0.0.1-SNAPSHOT.apk, AndroidManifest.xml]
[INFO] android.devices parameter not set, using all attached devices
[INFO] Device 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 found.
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :   Successfully uninstalled br.com.calcdesempenho
[INFO] android.devices parameter not set, using all attached devices
[INFO] Device 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 found.
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :   Successfully installed C:\Users\Rafael\.m2\repository\br\com\calcdesempenho\calc-desempenho\0.0.1-SNAPSHOT\calc-desempenho-0.0.1-SNAPSHOT.apk
[INFO] C:\Desenvolvimento\android-sdk\build-tools\19.0.0\aapt.exe [dump, xmltree, C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\CalcDesempenho-Test-1.0.apk, AndroidManifest.xml]
[INFO] android.devices parameter not set, using all attached devices
[INFO] Device 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 found.
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :   Successfully uninstalled br.com.calcdesempenho.desempenhotest
[INFO] android.devices parameter not set, using all attached devices
[INFO] Device 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 found.
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :   Successfully installed C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\CalcDesempenho-Test-1.0.apk
[INFO] 
[INFO] --- android-maven-plugin:3.9.0-rc.1:internal-integration-test (default-internal-integration-test) @ CalcDesempenho-Test ---
[INFO] android.devices parameter not set, using all attached devices
[INFO] Device 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 found.
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :   Running instrumentation tests in br.com.calcdesempenho.desempenhotest
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :     Run started: br.com.calcdesempenho.desempenhotest, 0 tests:
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :     Run failed: Instrumentation run failed due to 'java.io.IOException'
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :     Run ended: 0 ms
[INFO]   Tests run: 0,  Failures: 0,  Errors: 0
[INFO] 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :   Report file written to C:\Users\Rafael\Dropbox\Estudos\Apps Android Exemplos\desempenhotest\target\surefire-reports\TEST-192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.866s
[INFO] Finished at: Sun Sep 14 01:05:32 BOT 2014
[INFO] Final Memory: 26M/356M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.9.0-rc.1:internal-integration-test (default-internal-integration-test) on project CalcDesempenho-Test: 192.168.56.101_5555_Genymotion_GoogleGalaxyNexus-4.3-API18-720x1280 :   Test run failed to complete: Instrumentation run failed due to 'java.io.IOException' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by SierraGolf** [comment] 2015-01-10 15:53
@chiavegatto the problem is in your setup. your are using the html formatter which was not supported in 1.1.5 so you could not see your mistake in that version.

however in version 1.1.8 the html formatter is now supported and the path [target/cucumber](https://github.com/chiavegatto/TDC-2014-POA/blob/master/TDC-2014-POA/desempenhotest/src/main/java/br/com/calcdesempenho/desempenhotest/StepDefCalDesempenho.java#L27) can not be created by cucumber since it is located on the device. if you would choose ```/data/data/br.com.calcdesempenho/```for example you would have no problem.

so in order to use the html formatter you need to specify a valid path on the android device and use for example the maven android plugin to copy all those files at the end of the execution onto your machine.

btw. you project had some problems:
* br.fpf.test.sqlagent:sql-agent:1.1 is not in maven central, but it also does not seem to be used
* at least one test is failing, du to the fact that most of the stuff seems to be written in protuguese I am unsure if this is intended
* you have quite a few unnecessary dependencies declared

one last tip, if you are having problems try to look at the logcat and use the filters wisely. this is the exception you should have found:

```
01-10 12:42:22.762    2430-2444/? E/AndroidRuntime﹕ FATAL EXCEPTION: Instr: cucumber.api.android.CucumberInstrumentation
    cucumber.runtime.CucumberException: java.io.IOException: Failed to create directory /target/cucumber
            at cucumber.runtime.formatter.HTMLFormatter.reportFileOutputStream(HTMLFormatter.java:231)
            at cucumber.runtime.formatter.HTMLFormatter.jsOut(HTMLFormatter.java:219)
            at cucumber.runtime.formatter.HTMLFormatter.uri(HTMLFormatter.java:59)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at cucumber.runtime.Utils$1.call(Utils.java:34)
            at cucumber.runtime.Timeout.timeout(Timeout.java:13)
            at cucumber.runtime.Utils.invoke(Utils.java:30)
            at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:243)
            at $Proxy8.uri(Native Method)
            at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:158)
            at cucumber.runtime.android.CucumberExecutor.execute(CucumberExecutor.java:113)
            at cucumber.api.android.CucumberInstrumentationCore.start(CucumberInstrumentationCore.java:88)
            at cucumber.api.android.CucumberInstrumentation.onStart(CucumberInstrumentation.java:26)
            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
     Caused by: java.io.IOException: Failed to create directory /target/cucumber
            at cucumber.runtime.io.URLOutputStream.ensureParentDirExists(URLOutputStream.java:53)
            at cucumber.runtime.io.URLOutputStream.<init>(URLOutputStream.java:33)
            at cucumber.runtime.io.URLOutputStream.<init>(URLOutputStream.java:24)
            at cucumber.runtime.formatter.HTMLFormatter.reportFileOutputStream(HTMLFormatter.java:229)
            at cucumber.runtime.formatter.HTMLFormatter.jsOut(HTMLFormatter.java:219)
            at cucumber.runtime.formatter.HTMLFormatter.uri(HTMLFormatter.java:59)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at cucumber.runtime.Utils$1.call(Utils.java:34)
            at cucumber.runtime.Timeout.timeout(Timeout.java:13)
            at cucumber.runtime.Utils.invoke(Utils.java:30)
            at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:243)
            at $Proxy8.uri(Native Method)
            at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:158)
            at cucumber.runtime.android.CucumberExecutor.execute(CucumberExecutor.java:113)
            at cucumber.api.android.CucumberInstrumentationCore.start(CucumberInstrumentationCore.java:88)
            at cucumber.api.android.CucumberInstrumentation.onStart(CucumberInstrumentation.java:26)
            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

I am closing the issue because it is invalid.

**Closed by SierraGolf** 2015-01-10 15:53 UTC
