### ISSUE TITLE
Upgrading from 7.1.0 to 7.2.0 failed

### ISSUE THREAD

**Issue by andre-aktivconsultancy** [cucumber/cucumber-jvm#2454] opened 2022-01-04 12:47 UTC
**Describe the bug**
I attempted to upgrade from version 7.1.0 to 7.2.0. This failed in our CI/CD pipeline. 

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in Cucumber
[ERROR] Cucumber.Cucumber  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "io.cucumber.cienvironment.CiEnvironment$Git.getRemote()" because "git" is null
```
Running this locally works without issue. This seems related to https://github.com/cucumber/cucumber-jvm/pull/2438 My best guess is that the CI environment (Jenkins) is detected which triggers the assembling of the Git metadata and this fails for unknown reason.

Happy to provide any additional info, not sure what is relevant though.

**To Reproduce**
Well, I am not completely sure. I can only reproduce it in our CI/CD pipeline. Jenkins executes the build, a docker container is created in which the actual build is performed which runs some tests with Cucumber.

**Expected behavior**
Not to fail with a NullPointerException.

**Your Environment**
 - cucumber: 7.2.0
 - Docker build image: Debian 10, Maven 3.8.3
 - Jenkins 2.319.1

**Comment by aslakhellesoy** [comment] 2022-01-04 13:34
Hi - this seems to be a regression from #2438 - I'll have a look

**Comment by aslakhellesoy** [comment] 2022-01-04 13:35
Do you have a full stack trace?

**Comment by aslakhellesoy** [comment] 2022-01-04 13:47
I've submitted a fix in #2455.

I assume you're using https://plugins.jenkins.io/git/. If you pass the environment variables defined [here](https://github.com/cucumber/ci-environment/blob/402c9c7dc5d4cd8b340b5fbb30ee07f40c537e0d/CiEnvironments.json#L113-L120) to your docker container, it should work with 7.2.0.

Even after we merge #2455 and make a new release you'll have to pass those environment variables if you want git links to show up in Cucumber Reports.

**Comment by mpkorstanje** [comment] 2022-01-04 16:22
Fixed in v7.2.1.

**Closed by mpkorstanje** 2022-01-04 16:22 UTC

**Comment by aslakhellesoy** [comment] 2022-01-04 17:17
Thanks @mpkorstanje !

**Comment by andre-aktivconsultancy** [comment] 2022-01-05 07:54
@aslakhellesoy @mpkorstanje 
Thanks for the quick response to this! Works like a charm :)

> Do you have a full stack trace?
This was all that got logged. I don't think have reduced the log level for Cucumber in our build. So it seems to me that this was all that got logged.


> Even after we merge #2455 and make a new release you'll have to pass those environment variables if you want git links to show up in Cucumber Reports.

Thanks for clarifying. We don't really need that info in the Cucumber reports. But good to know anyway.
