### ISSUE TITLE
cucumber.runtime.io.HelpersTest.computes_file_path_for_file_url test fails in windows

### ISSUE THREAD

**Issue by fmarmar** [cucumber/cucumber-jvm#963] opened 2016-02-14 19:49 UTC
When I tried to compile the project in a windows machine the test method 'computes_file_path_for_file_url' from test class 'cucumber.runtime.io.HelpersTest' fails with the given assertion error

org.junit.ComparisonFailure: expected:<[D:\Users\First Last\.m2\repository\info\cukes\cucumber-java\1.2.2\]cucumber-java-1.2.2....> but was:<[/Users/First Last/.m2/repository/info/cukes/cucumber-java/1.2.2/]cucumber-java-1.2.2....>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at cucumber.runtime.io.HelpersTest.computes_file_path_for_file_url(HelpersTest.java:28)

**Comment by pernalin** [comment] 2016-03-13 00:00
Duplicate of https://github.com/cucumber/cucumber-jvm/pull/897

**Closed** 2016-08-17 09:29 UTC
