### ISSUE TITLE
Pax-exam module references nexus.codehaus.org

### ISSUE THREAD

**Issue by dkowis** [cucumber/cucumber-jvm#1111] opened 2017-04-03 20:54 UTC
## Summary
```
[ERROR]   The project info.cukes:pax-exam:[unknown-version] (/home/travis/build/cucumber/cucumber-jvm/examples/pax-exam/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for info.cukes:pax-exam:[unknown-version]: Could not transfer artifact info.cukes:cucumber-jvm:pom:1.2.5-SNAPSHOT from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org and 'parent.relativePath' points at wrong local POM @ line 4, column 13: Unknown host nexus.codehaus.org -> [Help 2]
```
## Expected Behavior
A successful travis build.
## Current Behavior
Build dies D:

## Possible Solution

Find the proper location for it, and don't reference nexus.codehaus.org, or remove the example if it's too far gone. This should be relatively easy to fix, anyone could duplicate it locally, just by trying to run mvn install for java 7 (which would include the pax-exam) example.
```
$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
$ mvn -q install -P examples
```

## Steps to Reproduce (for bugs)

Run a travis-CI build. or

```
$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
$ mvn -q install -P examples
```

## Context & Motivation

It's reducing confidence in our pull requests, because "all the checks fail"

**Comment by mlvandijk** [comment] 2017-08-20 16:26
Cannot reproduce or find the nexus.codehaus.org reference, so I'm closing this issue. If you feel this is incorrect, feel free to reopen

**Closed by mlvandijk** 2017-08-20 16:26 UTC
Labels: Build
