### ISSUE TITLE
cucumber.features property completely ignored when running through JUnit 5

### ISSUE THREAD

**Issue by EricBuist** [cucumber/cucumber-jvm#2206] opened 2021-01-14 19:03 UTC
Hi,
I'm trying to make use of cucumber-junit-platform-engine so Cucumber runs through JUnit 5. I have dependencies to JUnit 5.5.1 and Cucumber 6.9.0 in my POM file, and I have a marker test class annotated with @Cucumber. The test class is named CucumberTest, so it ends with Test and can be detected by Surefire. However, no matter what I try, Cucumber never detects the .feature files. They were originally in src/features, I tried to relocate them in src/test/resources/features thinking Cucumber would crawl the classpath, but to no avail. I read about the cucumber.features property and tried to set it to src/features, then src/test/resources/features, then features, then classpath:features, then classpath:/features, then /features, to no avail. I also tried features2 (non-existing directory) to force an error, making sure the path is taken into consideration. Not only no tests are run, but I never get any error message of any kind.
I tried to put this cucumber.features property in src/test/resources/junit-platform.properties and pass it explicitly to mvn -Dcucumber.features=... No tests get loaded.
At this point, I think the cucumber.features property is just ignored, preventing configuration of the path where .feature files are read. The documentation seems to let me believe the cucumber.features property only accepts a comma-separated list of .feature files, but I need to be able to pass a directory, not having to enumerate each and every .feature file in a .properties file, especially since that needs to go all on a single line.

**Comment by mpkorstanje** [comment] 2021-01-14 22:58
Duplicate of https://github.com/cucumber/cucumber-jvm/issues/2175

**Closed by mpkorstanje** 2021-01-14 22:58 UTC
