### ISSUE TITLE
Formatter#scenario#getTags() method does not returns tags specified at Examples level

### ISSUE THREAD

**Issue by mrunalgosar** [cucumber/cucumber-jvm#1327] opened 2018-03-03 18:19 UTC
## Summary

`Formatter#scenario#getTags()` method does not returns tags specified at Examples level

## Expected Behavior

Gherkin Formatter#scenario#getTags() should also return tags specified at the example level.

## Current Behavior

Currently it only returns tags specified at the Scenario or Feature level.

## Steps to Reproduce (for bugs)

Assume below Examples table:

```
@ex1
    Examples: Mobile
      | item   |
      | iphone |

  @ex2
    Examples: Firm
      | item    |
      | samsung |
```
In the above example table user has tagged to multiple examples table.
Here when we run our test with a custom Formatter then no method exposes this tags.

## Context & Motivation

I am trying to implement a custom Reporter but the example level tags information is not available.

## Your Environment

* Version used: 1.2.5
* Operating System and version: windows 7
* Link to your project: N/A

**Comment by mlvandijk** [comment] 2018-03-03 19:26
Might be similar/related to: https://github.com/cucumber/cucumber-jvm/issues/849
Could you please try with v2.0.0 or up? (We're currently at 2.3.1)

**Comment by brasmusson** [comment] 2018-03-04 19:42
Duplicate of #648, #686 and #849. This is fixed in Cucumber-JVM v2.x.x.

**Closed by brasmusson** 2018-03-04 19:42 UTC
