### ISSUE TITLE
Multiple ParameterTypes with same type

### ISSUE THREAD

**Issue by bojanv55** [cucumber/cucumber-jvm#1866] opened 2020-01-22 10:12 UTC
Is it possible to register same type for multiple named ParameterTypes ?

I have registered the following:

```
@ParameterType(name="prop1", value="\"(.*)\"")
  public Integer getp1(String p1) {
    return mapper.map1(p1);
  }

  @ParameterType(name="prop2", value="\"(.*)\"")
  public Integer getp2(String p2) {
    return mapper.map2(p2);
  }
```

and the exception I get is  (depending on a run):

> Undefined parameter type {prop2}. Please register a ParameterType for {prop2}.

 or 

> Undefined parameter type {prop1}. Please register a ParameterType for {prop1}

I guess this is due to cucumber already registerd String->Integer somewhere and second registration with same type description fails.

**Comment by bojanv55** [comment] 2020-01-22 10:18
This is not a big deal

**Comment by mpkorstanje** [comment] 2020-01-22 10:21
> Is it possible to register same type for multiple named ParameterTypes ?

Yes.

> I guess this is due to cucumber already registerd String->Integer somewhere and second registration with same type description fails.

That is not correct. Parameter types are registered by their method name. 

Based on the information you've provided I can't reproduce the problem. Could you try to reproduce the problem in a small git project?

https://github.com/cucumber/cucumber-java-skeleton would be a good base.

**Comment by bojanv55** [comment] 2020-01-22 10:30
I guess it has to do something with me using JUnit5 instead standard JUnit4 and running it with `"Run all features in: test"` in IntelliJ. 

It works if I run it using `maven` or` run 'All Test'` in IntelliJ.

**Comment by mpkorstanje** [comment] 2020-01-22 10:34
This sounds like a classpath scanning issue.

Are you using `cucumber-junit-platform-engine` to run your tests?

If so do you have `cucumber.clue` set in `junit-platform.properties`? Can you try setting it to the package name of your glue classes?

If that makes the problem go away, please put a break point here and see which classes Cucumber fails to scan:

https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/io/cucumber/core/resource/ClasspathScanner.java#L102

**Comment by bojanv55** [comment] 2020-01-22 10:42
I'm using `cucumber-junit-platform-engine`.

Inside `junit-platform.properties` I have only `cucumber.execution.parallel.enabled=true`. How to set `cucumber.clue`?

**Comment by mpkorstanje** [comment] 2020-01-22 10:45
Add a new line to `junit-platform.properties` with:

```
cucumber.glue=com.example.package.of.glue.classes
```

And replace `com.example.package.of.glue.classes` with the name the package all your glue classes are in. 

Note: I previously misspelled `glue` and wrote `clue` instead.

**Comment by bojanv55** [comment] 2020-01-22 10:53
Seems like when I `"Run all features in: test"` in IntelliJ it adds `...CucumberJvm5SMFormatter --glue some.namespace.where.my.step.defs.are` but my `@ParameterType` are few packages above. When I run tests from maven, I do not see that `--glue` parameter added.

**Comment by mpkorstanje** [comment] 2020-01-22 10:58
If you edit the run config to the right glue package? Does that fix it? You can also permanently fix it by changing the run config template for Cucumber.

**Comment by bojanv55** [comment] 2020-01-22 11:07
No. Same thing. It just keeps the same `...CucumberJvm5SMFormatter --glue some.namespace.where.my.step.defs.are`.  Run config template - I guess this is in intelliJ config.

**Comment by mpkorstanje** [comment] 2020-01-22 11:29
Okay. I'll close this then.

**Closed by mpkorstanje** 2020-01-22 11:29 UTC
Labels: Feature Request
