### ISSUE TITLE
@PostConstruct & @PreDestroy run after scenario finishes

### ISSUE THREAD

**Issue by hutchy2570** [cucumber/cucumber-jvm#325] opened 2012-05-18 08:15 UTC
We've got a suite of scenarios which rely on a number of users being created.  To accomplish this we currently have a @Before & @After combination that creates & destroys the users before & after each scenario.  Obviously as this suite grows this becomes quite an overhead so we're wanting to have this happen once before & after the entire suite.

We've tried reimplementing this with @PostConstruct & @PreDestroy but these don't get called until after each scenario has run (effectively both acting like @After).

**Comment by CluEleSsUK** [comment] 2018-09-03 14:26
I have just run into this bug also using the latest spring and cucumber/cucumber-spring.

Essentially, when you run a Spring test and there is a component in your test context as below
```
public class LifecycleHooks {
  @PreDestroy
  public void onDestroy() {
    System.out.println("hello world");      
  }
}
```
Expected behaviour is`hello world` to only be output once for the whole application (as context is shared between Scenarios).  The actual behaviour however is that it is run once per Scenario.

**Comment by mpkorstanje** [comment] 2018-09-03 14:55
Are you using `@DirtiesContext` or `@Scope("cucumber-glue")` for this bean?

Just to double check. The maven groupId has changed. Are you using v3?

**Comment by CluEleSsUK** [comment] 2018-09-03 15:04
Not using `@DirtiesContext` nor `@Scope("cucumber-glue")`
Currently using the latest v2, due to some compatibility issues when we first tried v3

**Comment by mpkorstanje** [comment] 2018-09-03 15:53
Okay thanks. I currently don't have the bandwidth to look into this anytime soon. 

If you want to have a go at fixing this a good place to start would be the SpringFactory. 

Cucumber creates a Spring `TestContextManager` and informs it when a scenario has [started](
https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java#L165) and [finished](
https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java#L197).

As all life cycle of the Spring beans is controlled by the `TestContextManager` I suspect the problem can be found there somewhere.

**Comment by mlvandijk** [comment] 2018-10-30 13:37
Unfortunately, I was unable to reproduce this using v2.3.1 (as v2 was mentioned). To do so I added the `LifecycleHooks` to my hooks, but when I ran my tests I only saw "Hello world" output once. Maybe I'm missing some information. I'm closing this issue for now. Please to reopen if you can provide a [mcve](https://stackoverflow.com/help/mcve) I suggest closing this issue.

**Closed by mlvandijk** 2018-10-30 13:37 UTC
Labels: Bug, Good First Issue, Hacktoberfest, Help Wanted, Spring
