### ISSUE TITLE
cucumber.runtime.CucumberException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by G4gan** [cucumber/cucumber-jvm#1562] opened 2019-02-20 09:43 UTC
cucumber.runtime.CucumberException: java.lang.NullPointerException
--
I am using Cucumber-Maven-Junit as a API automation frameowrk.

**Refer issue** [Cucumber_NPE](https://issues.apache.org/jira/browse/SUREFIRE-1625)
====
Framework was developed on Windows OS where everything was working fine when execution was done using maven commands (mvn clean ,test)..

Now our requirement is to run on Debian OS (Ubuntu.)

Version : Linux ubuntu 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Where I am getting NPE exception on execution.**
Please refer pom.xml and mvn test logs in the link attached.
**Observation**
I am not sure whether I am missing any configuration or is it surefireplugin issue.
I have tried using maven-surefire-plugin version 2.21.0 and 3.0.0-M2

**Any help would be highly appreciated.**

@mpkorstanje  I got you reference from Tibor Digana a developer for Surefire-Plugin.
It would be great if you can provide your inputs on this.

**Comment by G4gan** [comment] 2019-02-20 09:52
Please find attachments for file.
pom.xml I have uploaded as a txt file coz .xml was not supported for upload.
[mvn_logs.txt](https://github.com/cucumber/cucumber-jvm/files/2883988/mvn_logs.txt)
[pom1.txt](https://github.com/cucumber/cucumber-jvm/files/2883998/pom1.txt)

**Comment by mpkorstanje** [comment] 2019-02-20 10:02
I don't have too much time to look into this. Would you be able to provide the problem as an MCVE? Preferably in a Github repository?

**Comment by mpkorstanje** [comment] 2019-02-21 04:08
On first glance it appears you are using a version of Cucumber that doesn't support rerun yet rerunning of failed tests.

This was introduced in v2. Please note that the groupId has changed.

**Comment by G4gan** [comment] 2019-02-21 09:34
could you let me know the correct pom dependency.
I am using this 
`<dependency>
    <groupId>info.cukes</groupId>
    <artifactId>cucumber-jvm</artifactId>
    <version>1.2.5</version>
    <type>pom</type>
</dependency>
`
Link : [Cucumber-Jvm](https://mvnrepository.com/artifact/info.cukes/cucumber-jvm/1.2.5)

**Comment by mpkorstanje** [comment] 2019-02-21 10:05
Have a look at the the skeleto project.

https://github.com/cucumber/cucumber-java-skeleton

**Comment by G4gan** [comment] 2019-02-23 04:09
@mpkorstanje I tried following same structure for my pom but still getting exceptions.

**Comment by mpkorstanje** [comment] 2019-02-23 05:25
Did you change to the latest version?

For a start you may even want to start with the skeleton and configure it to rerun failed tests.

Please do include your pom.

**Comment by nhojpatrick** [comment] 2019-02-23 10:08
@mpkorstanje i'm happy to look into this for you

@G4gan what command line are you executing and what maven version are you using?

i've tried most combinations of;
cucumber 1.2.x and 4.x
maven 3.0.x, 3.1.x, 3.2.x, 3.3.x, 3.4.x, 3.5.x and 3.6.x
junit 4.12 and 5.x
surefire ... due to junit 5 issues i've only done a few combinations so 2.22.1 and 3.0.0-M3 are two that I've used recently that i know work

also most of my cucumber testing i do using the failsafe plugin, so the verify command, not surefire plugin and test command.

**Comment by mpkorstanje** [comment] 2019-02-23 10:11
Cheers!

**Comment by G4gan** [comment] 2019-02-25 06:21
@mpkorstanje thanks for your response.
@nhojpatrick thanks for looking into this.
I am using 
`gagan@ubuntu:~$ mvn --version
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-20-generic", arch: "amd64", family: "unix"`

I have tried ruuning my pom using
`mvn test and 
mvn -Dcucumber.options="..." test` 

Attaching my pom and with different scenarios I have tried.
Note for pom.xml name I just used here for better nomenclature.
Scenario1:mvn verify
![scenario1_withfailsafeplugin](https://user-images.githubusercontent.com/47812602/53317120-6fc50480-38f0-11e9-86f3-ac4857c29073.PNG)
[Scenario_1_pom.txt](https://github.com/cucumber/cucumber-jvm/files/2899165/Scenario_1_pom.txt)

Scenario2:mvn verify
![scenario2_failsafeconfiguration](https://user-images.githubusercontent.com/47812602/53317233-da764000-38f0-11e9-9b40-6689518810b1.PNG)

[Scenario_2_pom.txt](https://github.com/cucumber/cucumber-jvm/files/2899166/Scenario_2_pom.txt)

Sceanrio3: mvn test
[Scenario3_pom.txt](https://github.com/cucumber/cucumber-jvm/files/2899200/Scenario3_pom.txt)

![sceanro3_maventest_output](https://user-images.githubusercontent.com/47812602/53317907-7608b000-38f3-11e9-8bf1-dfb06169d4dc.PNG)

Let me know your views if I am missing anything in my pom

**Comment by G4gan** [comment] 2019-03-06 10:50
@mpkorstanje @nhojpatrick 
Could you please provide your inputs on these.
Would be great if you me know for Sceanrio3: mvn test
thanks

**Comment by mpkorstanje** [comment] 2019-03-06 12:07
So as I mentioned before, I see that you are still using an old version of cucumber in your pom.

```
<dependency>
  <groupId>info.cukes</groupId>
   <artifactId>cucumber-java</artifactId>
   <version>1.2.5</version>
   <scope>compile</scope>
</dependency>
```
Please upgrade to the latest version of Cucumber first:
```
<dependency>
  <groupId>io.cucumber</groupId>
  <artifactId>cucumber-jvm</artifactId>
  <version>4.2.5</version>
</dependency>
```

**Comment by G4gan** [comment] 2019-03-07 12:42
@mpkorstanje thanks for the reply.
I am getting this now

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:19 min
[INFO] Finished at: 2019-03-07T18:07:04+05:30
[INFO] Final Memory: 15M/46M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ApiAutomation: Could not resolve dependencies for project api:ApiAutomation:jar:1.0-SNAPSHOT: Could not find artifact io.cucumber:cucumber-jvm:jar:4.2.5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by mpkorstanje** [comment] 2019-03-07 12:53
Sorry. Wrong artefact.
```
<dependency>
  <groupId>io.cucumber</groupId>
  <artifactId>cucumber-java</artifactId>
  <version>4.2.5</version>
</dependency>
```

**Comment by G4gan** [comment] 2019-03-07 13:53
**Now i am getting this error for initialization**

![error_1](https://user-images.githubusercontent.com/47812602/53961398-7cc2ce80-410e-11e9-9fd8-e38cbf30307e.PNG)

**Comment by G4gan** [comment] 2019-03-07 14:40
I tried adding "Test " at the end of my runner file class.
But niow I am getting this error


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project ApiAutomation: Compilation failure
[ERROR] <directory-path>/ApiRunnerTest.java:[32,7] error: class ApiRunnetTest is public, should be declared in a file named ApiRunnetTest.java
[ERROR]

Any clue where I am missing

**Comment by mlvandijk** [comment] 2019-03-07 14:43
This is a Java error: [ERROR] /ApiRunnerTest.java:[32,7] error: class ApiRunnetTest is public, should be declared in a file named ApiRunnetTest.java  
Looks like you have a typo in your class name: ApiRunne**t** (a T at the end) instead of ApiRunner (an R at the end)

**Comment by G4gan** [comment] 2019-03-07 14:59
Yes thanks @mlvandijk @mpkorstanje 

I have re-corrected the class file name but still I am getting this error .


[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running <directory-path>.testrunner.ApiRunnerTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.167 s <<< FAILURE! - in com.ibm.cis.testrunner.ApiRunnerTest
[ERROR] initializationError( <directory-path>.testrunner.ApiRunnerTest)  Time elapsed: 0.026 s  <<< ERROR!
java.lang.NoClassDefFoundError: gherkin/IGherkinDialectProvider
Caused by: java.lang.ClassNotFoundException: gherkin.IGherkinDialectProvider

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ApiRunnerTest.initializationError » NoClassDefFound gherkin/IGherkinDialectPro...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:55 min
[INFO] Finished at: 2019-03-07T20:24:58+05:30
[INFO] Final Memory: 29M/79M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project ApiAutomation: There are test failures.

**Comment by mlvandijk** [comment] 2019-03-07 15:08
Could you post the dependencies from your pom.xml, please?

**Comment by G4gan** [comment] 2019-03-07 15:15
[pom11.txt](https://github.com/cucumber/cucumber-jvm/files/2941912/pom11.txt)

This is my pom file which I am using

**Comment by mlvandijk** [comment] 2019-03-07 15:21
Try removing the Gherkin dependency? You should get that through your Cucumber dependencies. And make sure you are using the same version for Cucumber dependencies. (you have 4.2.3 and 4.2.5 now). Also, you don't need `cucumber-core` explicitly.

**Comment by mlvandijk** [comment] 2019-03-07 15:22
Note: you can specify the cucumber version once, and make sure to use it for all your cucumber dependencies, like so:

```
    <properties>
        <cucumber.version>4.2.6</cucumber.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java8</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

**Comment by G4gan** [comment] 2019-03-07 15:44
I have made changes as suggested by you
now mvn test is giving Build Success but it it not executing my apiRunner.
new pom.xml
[pom11.txt](https://github.com/cucumber/cucumber-jvm/files/2942051/pom11.txt)

**Comment by mlvandijk** [comment] 2019-03-07 16:06
A different error. Progress! :)

**Comment by mlvandijk** [comment] 2019-03-07 16:07
And what about `mvn clean install`? (I'd have to lookup details for maven build phases on what happens where)

**Comment by G4gan** [comment] 2019-03-08 12:37
@mlvandijk @mpkorstanje 
Getting error **Caused by: java.lang.ClassNotFoundException: gherkin.formatter.Reporter**
 I am using these version for 
Cucumber , Gherkin and surefire-plugin
`
			
                    <groupId>io.cucumber</groupId>
                    <artifactId>gherkin</artifactId>
                    <version>5.1.0</version>
	
			
			 <dependency>
				  <groupId>io.cucumber</groupId>
				  <artifactId>cucumber-java</artifactId>
				  <version>4.2.5</version>
			</dependency>
				
			<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M3</version>
						<configuration>
                            <includes>
                              <include>ApiRunnerTest.java</include>
                              </includes>
                        </configuration>
			</plugin>
`
---------------------------------------------------------------------------------------------------
And error I am getting is 


[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.testrunner.ApiRunnerTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.265 s <<< FAILURE! - in com.testrunner.piRunnerTest
[ERROR] initializationError(com.testrunner.ApiRunnerTest)  Time elapsed: 0.027 s  <<< ERROR!
java.lang.NoClassDefFoundError: gherkin/formatter/Reporter
Caused by: java.lang.ClassNotFoundException: gherkin.formatter.Reporter

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ApiRunnerTest.initializationError » NoClassDefFound gherkin/formatter/Reporter
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.263 s
[INFO] Finished at: 2019-03-08T10:52:01+05:30
[INFO] Final Memory: 22M/57M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test

**Comment by mpkorstanje** [comment] 2019-03-10 13:27
I strongly suspect you have a custom plugin that also needs to be upgraded. But rather then trying to upgrade your cucumber version one message at a time perhaps you can start by reproducing your original problem using the [cucumber-java-skeleton](https://github.com/cucumber/cucumber-java-skeleton).

Then once you confirm it works you can migrate your features step by step. By going from working version to working version in small steps it becomes easier to work out for yourself what you're doing wrong.

I'm going to close this issue now as the original problem --trying to rerun failed tests-- is not supported in v1.2.5.

**Closed by mpkorstanje** 2019-03-10 13:27 UTC
