### ISSUE TITLE
Reports does not work 

### ISSUE THREAD

**Issue by MoaadAmer** [cucumber/cucumber-jvm#1303] opened 2017-12-17 15:23 UTC
https://stackoverflow.com/questions/47817891/cucumber-generates-blank-html-report

Cucumber version 1.2.5

**Comment by brasmusson** [comment] 2017-12-17 19:25
Which version of Cucumber-JVM are you using?

**Comment by MoaadAmer** [comment] 2017-12-25 13:29
@brasmusson  Cucumber version 1.2.5

**Comment by haroon-sheikh** [comment] 2017-12-28 11:37
@MoaadAmer Would you be able to share the failing example (maybe on gist.github.com)? I'm not able reproduce the issue on 1.2.5 or latest 2.3.1.

**Comment by brasmusson** [comment] 2017-12-28 19:34
@haroon-sheikh Do you have a `Before` hook that calls `write` on the `Scenario` argument of the hook? To me it looks like that is triggering the problem.

**Comment by MoaadAmer** [comment] 2017-12-31 09:46
@brasmusson yes i do have a before hook with argument of type Scenario

**Comment by brasmusson** [comment] 2018-01-01 19:44
Calling `write` on the `Scenario` argument of a hook will add a `formatter.write` call in the `report.js` file. The javascripts functions of https://github.com/cucumber/cucumber-html will display the content of the `formatter.write` call below the preceding step. For before hooks of the first scenario executed, there does not exist any preceding step, since no (gherkin) step has been executed yet, therefore the report will be blank from this point on (for `formatter.write` calls from before hooks of subsequent scenarios, the content will be displayed below the last step of the preceding scenario, which is incorrect but the report will at least not be blank).

To fix this the https://github.com/cucumber/cucumber-html project need to be updated. However, since the plan is to replace that project, see https://github.com/cucumber/cucumber-html/pull/44, I'm not sure anyone in the core team will take on that work.

The workaround is to not call `write` on the `Scenario` argument of before hooks, if the html-formatter is used.

**Comment by MoaadAmer** [comment] 2018-01-04 14:10
Okay Thanks !

**Comment by brasmusson** [comment] 2018-01-04 17:32
The issue exist in [cucumber-html](https://github.com/cucumber/cucumber-html) v0.2.6, which is the latest released version of cucumber-html.

**Comment by MoaadAmer** [comment] 2018-01-04 18:33
So that defect is also in cucumber 2.3.1 ?

**Comment by brasmusson** [comment] 2018-01-04 19:07
The issue will exist in all Cucumber-JVM versions until new version of cucumber-html is released with a fix.

**Closed** 2018-01-04 19:28 UTC
