### ISSUE TITLE
Using cucumber-spring does not share Spring context when using parallel (methods) surefire settings

### ISSUE THREAD

**Issue by dom54** [cucumber/cucumber-jvm#1846] opened 2019-12-20 07:48 UTC
## Summary

I have 3 feature files, with a single StepDefinition.   When running in single threaded mode, everything is perfect.   When running with the maven surefire plugin, using parallel as methods,  I get a spring context created per thread, which I cannot have (startup time of the app would mean no benefit to threading)

```java
@WebAppConfiguration
@ContextHierarchy({
        @ContextConfiguration(classes = { TestConfiguration.class }, loader = AnnotationConfigWebContextLoader.class),
        @ContextConfiguration(classes = { ServletConfiguration.class }, loader = AnnotationConfigWebContextLoader.class)
})
public class DefaultSteps {
```

```xml
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <parallel>methods</parallel>
                    <threadCount>8</threadCount>
```
I am working on a test case to share

## Expected Behavior

The problem is the code uses a "TestContext" which binds a context to ThreadLocal.

So I worked around this by putting my own bootstrapper
```java
@BootstrapWith(value = MultiThreadedAwareSpringBootstrapper.class)
public class DefaultSteps {
```

```java
public class MultiThreadedAwareSpringBootstrapper extends org.springframework.test.context.web.WebTestContextBootstrapper {

    @Override
    public TestContext buildTestContext() {
        return new DefaultTestContext(getBootstrapContext().getTestClass(), buildMergedContextConfiguration(),
                new DefaultCacheAwareContextLoaderDelegate()); // dont pass in a context ,which will then use a static default cache of contexts, i.e. share between threads
    }

}
```

## Current Behavior
This works, except once in a while it blows up (SpringFactory seems not to be thread safe)

```java
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.refacted.redacted.acceptance.glue.DefaultSteps' available: expected single matching bean but found 1: com.redacted.redacted.acceptance.glue.DefaultSteps


```
## Possible Solution
Make SpringFactory threadsafe...still investigating.

In particular this line is not thread safe (if the context is shared)
```java
context.getBeanFactory().registerScope(SCOPE_CUCUMBER_GLUE, new GlueCodeScope());
```

## Steps to Reproduce (for bugs)
Working on it...

**Comment by mpkorstanje** [comment] 2019-12-20 09:19
You are unfortunately not the first to have noticed this. If you want to help out you'd be most welcome but unfortunately it won't be trivial.

Have a look at #1583 and #1582 and #1470 for a possible solution.

I'll close this one.

**Comment by dom54** [comment] 2019-12-20 11:39
Im not sure I understand why its not trivial.  Adding a synchronized block *seems* to have fixed it for me.... (im using 4.8.0)

**Comment by mpkorstanje** [comment] 2019-12-20 11:50
Unfortunately `cucumber-spring` puts step definitions instances into the application context as beans. Hence the occasional `NoUniqueBeanDefinitionException` when two scenarios execute concurrently. 

The step definition instances contain the current state of a scenario. So swapping these out concurrently may result in leaking state between scenarios.

**Comment by dom54** [comment] 2019-12-20 14:49
But looking at the code it is intending to put them in as "cucumber-scope" beans, which are ThreadLocal scoped, which it does do.  So the instance of the bean is only ever in GlueCodeScope.

The method returns a bean and stores the bean in a thereadlocal context.

```java
 @Override
    public Object get(String name, ObjectFactory<?> objectFactory) {
        GlueCodeContext context = GlueCodeContext.getInstance();
        Object obj = context.get(name);
        if (obj == null) {
            obj = objectFactory.getObject();
            context.put(name, obj);
        }

        return obj;
    }
```

**Comment by dom54** [comment] 2019-12-20 14:57
(Im just trying to get to the bottom of why we think this is non trivial as the code looks to be doing everything required! Except for one or two lines of non-thread safe stuff in SpringFactory)

**Comment by mpkorstanje** [comment] 2019-12-20 15:01
```
    @Override
    public <T> T getInstance(final Class<T> type) {
        try {
            return beanFactory.getBean(type);
        } catch (BeansException e) {
            throw new CucumberBackendException(e.getMessage(), e);
        }
    }
```

So you're saying that `getInstance` should pull the beans from the current glue scope rather then the bean factory?

**Comment by mpkorstanje** [comment] 2019-12-20 15:03
Please feel free to send a PR!

**Comment by mpkorstanje** [comment] 2019-12-20 15:25
I've been working with the assumption that there was only one `cucumber-glue` scope active at once. If that assumption is not correct then you are onto a much better fix then what I had in mind.

**Comment by dom54** [comment] 2019-12-20 15:41
Yes, getInstance does pull out of current glue scope and current glue scope (of which there is one defined but delegates to a ThreadLocal) .  

There is definitely a race condition but not sure where...ill carry on trying to diagnose, but I feel like it will be a small fix

**Comment by dom54** [comment] 2019-12-20 16:43
Yes so I found the issue. I would say its more of a spring bug.

If two threads call (in DefaultListableBeanFactory)
public void registerBeanDefinition(String beanName, BeanDefinition beanDefinition)
There is a check to see if the definition already exists.  If it doesnt exist, it replaces in a ConcurrentHashMap the definition (in a synchronized block as well) **but it adds the bean name to a list without checking if it already exists**

```java
	synchronized (this.beanDefinitionMap) {
					this.beanDefinitionMap.put(beanName, beanDefinition);
					List<String> updatedDefinitions = new ArrayList<>(this.beanDefinitionNames.size() + 1);
					**updatedDefinitions.addAll(this.beanDefinitionNames);**
					updatedDefinitions.add(beanName);
					this.beanDefinitionNames = updatedDefinitions;
```

**Comment by mpkorstanje** [comment] 2019-12-20 16:47
Shouldn't be too much hardship to synchronize `registerStepClassBeanDefinition` and delete `FixBootstrapUtils`.

**Comment by mpkorstanje** [comment] 2019-12-20 16:58
Ah. No that won't work. It's the underlying application context that is shared.

**Comment by dom54** [comment] 2019-12-20 17:21
Away over Xmas so raised a quick PR which I believe will fix the issue0.  Please note it doesnt change the fact that you still get a context per thread by default (but this is easy to override see below)

```java
public class MultiThreadedAwareSpringBootstrapper extends org.springframework.test.context.web.WebTestContextBootstrapper {

    @Override
    public TestContext buildTestContext() {
        return new DefaultTestContext(getBootstrapContext().getTestClass(), buildMergedContextConfiguration(),
                new DefaultCacheAwareContextLoaderDelegate());
    }
```

**Comment by mpkorstanje** [comment] 2019-12-20 17:26
If I am not mistaken that is caused by: https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/main/java/io/cucumber/spring/FixBootstrapUtils.java#L47

Which is a class I'll enjoy deleting. 

Anyway. Enjoy the holidays!

**Comment by dom54** [comment] 2019-12-20 17:29
Yes you are right, but it might be desirable to have a context per feature , I am not sure really.. need to think about it.

Per thread is not very useful, per scenario might be useful... but if we are happy to get rid of "context per thread" as FixBootStrapUtils is doing, then yes we dont need that class anymore

**Comment by mpkorstanje** [comment] 2019-12-20 17:33
There is no concept of features when executing cucumber. We only deal with pickles (compiled scenarios, and examples). Each of these is assumed to be independent from the others.

Ofc. with the spring context that doesn't really work out, but at this point it is up to the test author to ensure everything can be executed in parallel (much like JUnit).

**Comment by mpkorstanje** [comment] 2019-12-20 17:34
And it is s a good thing we're working on major release now. So we can break everything - it just means writing more release notes. :laughing:

**Comment by dom54** [comment] 2019-12-20 19:44
ok - updated the PR to default the behaviour using a single context (rather than one per thread)

**Comment by dom54** [comment] 2019-12-20 19:49
https://github.com/cucumber/cucumber-jvm/pull/1848

I think its a bit tricky to have a deterministic test, what do you think?

**Closed** 2019-12-21 14:17 UTC
