### ISSUE TITLE
NPE when empty .feature file present

### ISSUE THREAD

**Issue by daczczcz1** [cucumber/cucumber-jvm#1355] opened 2018-04-24 07:20 UTC
## Summary

When an empty .feature file is present in the 'features' path specified in the runner 

## Expected Behavior

Even if a NullPointerException is to be thrown, there should be some information about the cause of it (e.g. name of empty file).
IMHO a warning log is preferrable.

## Current Behavior

This is the stack trace:

> java.lang.NullPointerException
> 	at cucumber.runtime.formatter.TestSourcesModel.parseGherkinSource(TestSourcesModel.java:161)
> 	at cucumber.runtime.formatter.TestSourcesModel.getFeature(TestSourcesModel.java:87)
> 	at cucumber.runtime.formatter.SerenityReporter.featureFrom(SerenityReporter.java:180)
> 	at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:150)
> 	at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:111)
> 	at cucumber.runner.EventBus.send(EventBus.java:28)
> 	at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132)
> 	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315)
> 	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:80)
> 	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:38)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
> 	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
> 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
> 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

## Possible Solution

As stated before: a warning when an empty .feature file is found

## Steps to Reproduce (for bugs)
1. Configure runner (haven't tried with other runner classes)
Runner:
```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(

        glue = {
                "*****.cucumberHook",
                "*****.citrus.steps",
                "*****.selenium.steps",
                "com.consol.citrus.cucumber.step.runner.core"
        },
        features = {
                "classpath:features",
        },
        format = {
                "json:target/cucumber-report/cucumber.json",
                "pretty",
                "html:target/site/cucumber-pretty",
                "json:target/cucumber.json"
        },
        junit = "--step-notifications",
        monochrome = true,
        tags = {
       "@New",
        }
      )
```
2. Add an empty .feature file
3. Start test (in my case through IntelliJ Idea)

## Context & Motivation

I found the problem cause straight away, since I was working on some new test cases. However, if these would have been changes introduced by another user in a big team, the time spent troubleshooting could be significantly longer.

## Your Environment

* Version used: 2.4.0
* Operating System and version: Windows 10 Enterptise

**Comment by mlvandijk** [comment] 2018-05-19 09:35
Hello @daczczcz1 - It looks like this is an issue with `serenity-cucumber`. I've created a small project to reproduce your issue [here](https://github.com/mlvandijk/npeissue). 
When I use `@RunWith(Cucumber.class)` (see the first commit), I get the following result:
```
0 Scenarios
0 Steps
0m0.014s
```
When I add the `serenity-cucumber` dependency (you haven't specified which version you use, so I took the latest from Maven Central, currently `1.9.7`), I see the following error:
```
java.lang.NullPointerException
	at cucumber.runtime.formatter.TestSourcesModel.parseGherkinSource(TestSourcesModel.java:161)
	at cucumber.runtime.formatter.TestSourcesModel.getFeature(TestSourcesModel.java:87)
	at cucumber.runtime.formatter.SerenityReporter.featureFrom(SerenityReporter.java:179)
	at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:149)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:110)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:81)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I'm therefore closing this issue; you'll have to address it with Serenity-BDD. Feel free to point to this issue and/or my repo.

**Closed by mlvandijk** 2018-05-19 09:35 UTC

**Comment by daczczcz1** [comment] 2018-05-19 16:54
Thank you for pointing that out. Indeed, I haven't tried changing the runner... I will open an issue in the Serenity-BDD project.

**Comment by mlvandijk** [comment] 2018-05-19 17:09
You're welcome!
