### ISSUE TITLE
Support custom cucumber expression types which accept multiple-line arguments, such as doc-strings

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber-jvm#1424] opened 2018-07-21 09:13 UTC
Hi,

I need to define a new parameter type which takes as argument a string on multiple lines (such as doc-string)
```
    Given the following json
  """
  {
    "field0": "value0",
    "field1": "value1"
  }
  """
```
```
 typeRegistry.defineParameterType(new ParameterType<>("json",
                "\\s*(.*)\\s*", Json.class, new Transformer<Json>() {
            @Override
            public Json transform(String s) throws Throwable {
                return new Json(s);
            }
        }));
```
```
@Given("the following json{json}")
public void setJson(Json json) {
   scenario.write(json.toString());
}
```

However, this does'n work since the doc-string is passed as second and last argument:
```
Given a string=                                                                            # SetSymbolsSteps.sets(String)
      cucumber.runtime.CucumberException: Step [the folowing json{json}] is defined with 1 parameters at 'ro.cucumber.core.features.stepdefs.Steps.setJson(Json) 
However, the gherkin step has 2 arguments:
```

This is just an example. I need to make more complex operations within the transform method, before the final argument is passed to the Java method.

Is there a solution to this problem, or any future features for this ?

**Comment by aslakhellesoy** [comment] 2018-07-21 10:31
Dupe of 
https://github.com/cucumber/cucumber/issues/440

**Closed by aslakhellesoy** 2018-07-21 10:31 UTC
