### ISSUE TITLE
cucumber-junit 1.2.0 is incompatible with junit 4.12

### ISSUE THREAD

**Issue by henrik242** [cucumber/cucumber-jvm#836] opened 2015-02-19 11:02 UTC
PublicClassValidator throws an Exception with message:
"The class cucumber.runtime.junit.ExamplesRunner is not public."

It looks like cucumber-junit 1.2.0 is incompatible with junit 4.12, see http://stackoverflow.com/a/25540276/13365 and https://groups.google.com/d/msg/cukes/w1QhqqqvJ8M/F9Pjoxe6Xb0J

**Comment by aslakhellesoy** [comment] 2015-02-19 11:07
Dupe of #792 and #794. Fixed in 1.2.2

**Closed by aslakhellesoy** 2015-02-19 11:07 UTC

**Comment by brendo10x** [comment] 2015-10-08 23:24
Use a versão do Junit na 4.11 que ai vai funcionar.
