### ISSUE TITLE
Get Feature file and Feature name in Before hook

### ISSUE THREAD

**Issue by dkirrane** [cucumber/cucumber-jvm#902] opened 2015-08-28 13:59 UTC
I'd like to be able the obtain the feature file name and Feature name in the `@Before` hook for logging purposes.

Something like the existing `Scenario` object:

```
    @Before("@Before")
    public void beforeScenario(Feature feature, Scenario scenario) {  
    }
```

**Comment by mikegolod** [comment] 2016-01-28 17:57
For me it would be useful to load resources from a feature file location

**Comment by hankscrpio** [comment] 2016-09-06 18:55
@sebrose 
I second the usefulness of adding the ability to retrieve the current Feature being executed, as this would largely help for logging purposes. For example, I screen record all tests and capture failures in a separate directory. Ideally, this directory would be named after the current Feature utilizing the current Scenario's name. If you have any questions about my setup, please let me know. Thanks!

**Comment by zhtaoang** [comment] 2017-01-26 20:03
There is a "scenarioId" in the scenario object, which contains both feature name and scenario name. Try using "scenario.getId()" to get them.

**Comment by tompahoward** [comment] 2017-05-18 23:02
Sorry to resurrect this, but `scenario.getId()` does provides a sanitised version of the feature name, *not* the actual feature name. For instance, For a feature called "TestCase0.0 Basic" and a scenario "Basic", `scenario.getId()` provides "testcase0.0-basic;basic" *not* "TestCase0.0 Basic;Basic"

However `scenario.getName()` *does* correctly return "Basic"

This issue has been tagged "Won't Fix". If possible, it would be great to get a explanation so we can understand why getting the Feature name would be a bad thing to do.

**Comment by brasmusson** [comment] 2017-06-18 18:15
With the newer version of the Gherkin library (v3.x.x and v4.x.x) the basis of executing is [Pickles](https://github.com/cucumber/cucumber/tree/master/gherkin#pickles) which the feature files are compiled into. The Pickle is a data structure designed for execution - avoiding feature file complexities like Background and Scenario Outline when executing, and does not assume that is was created from a feature file in the first place - in the future a compiler from markdown to Pickles may be developed. 

Since a Pickle does not contain any information about feature name (by design), it is impossible to provide feature name to Before or After Hooks in the coming Cucumber-JVM 2.0.0 that uses v4 of the Gherkin library (available as a [snapshot release](https://cucumber.io/docs/reference/jvm) - note that the groupId has changed to "io.cucumber").

To uniquely identify the source of the Pickle, the path of the (feature) file it came from and the line (or lines in case of Scenario Outline) in the file it was defined needs to be used - that is, the "uri" and "locations" attributes of the Pickles.

**Closed by brasmusson** 2017-06-18 18:15 UTC
Labels: Feature Request, Won't Fix

**Comment by vinodkeyaccess** [comment] 2018-10-17 09:35
@Before
public void setup(Scenario scenario) throws IOException {
		System.out.println(scenario.getId());
	}
**Output:**
**phptravels-test-login-001;**verify-that-user-is-able-to-login-into-system-successfully-by-providing-valid-username-and-password

Use split function if you want only feature file name;

@Before
	public void setup(Scenario scenario) throws IOException {
		System.out.println(scenario.getId().split(";")[0]);
	}
**Output:**
phptravels-test-login-001
