### ISSUE TITLE
Arity mismatch when using docstring in a step and supplying it as someMethod(String string)

### ISSUE THREAD

**Issue by jedi-tester** [cucumber/cucumber-jvm#1214] opened 2017-09-05 12:36 UTC
## Summary

feature file:
```
Feature: Something 
Scenario: Verify some value
        Given I have executed some methods
        When I execute following hive statement:
        """
        SELECT *
        FROM tablename
        """
        Then I expect some values from hive
```

and my step:
```
@When("^I execute following hive statement:$")
    public void iExecuteHiveQuery(String query) throws Throwable {
}
```

Throws 
Arity mismatch: Step Definition 'iExecuteHiveQuery(String) in file:/' with pattern [^I execute following hive statement:$] is declared with 1 parameters. However, the gherkin step has 0 arguments [].

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.2.5
* Operating System and version: Win 10
* Link to your project: NA

**Comment by aslakhellesoy** [comment] 2017-09-05 12:39
Can you please confirm what version you're using? ("Latest" isn't a version)

**Comment by jedi-tester** [comment] 2017-09-05 12:49
Sorry :) 
It's 1.2.5

And my cucumber dependencies:
```
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java8</artifactId>
            <version>${cucumber.ver}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.ver}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.ver}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>${cucumber.ver}</version>
            <scope>test</scope>
        </dependency>
```

**Comment by jedi-tester** [comment] 2017-09-05 12:56
Have just tried with 2.0.0 and updated my pom (I was using info.cukes instead of io.cucumber for some reason). But in any case, I'm still getting same error.
```
<dependency>
<groupId>io.cucumber</groupId>
<artifactId>cucumber-java8</artifactId>
<version>${cucumber.ver}</version>
<scope>test</scope>
</dependency>
<dependency>
<groupId>io.cucumber</groupId>
<artifactId>cucumber-java</artifactId>
<version>${cucumber.ver}</version>
<scope>test</scope>
</dependency>
<dependency>
<groupId>io.cucumber</groupId>
<artifactId>cucumber-junit</artifactId>
<version>${cucumber.ver}</version>
<scope>test</scope>
</dependency>
<dependency>
<groupId>io.cucumber</groupId>
<artifactId>cucumber-picocontainer</artifactId>
<version>${cucumber.ver}</version>
<scope>test</scope>
</dependency>
```

**Comment by mlvandijk** [comment] 2017-09-09 15:37
Hello @jedi-tester, I've tried to reproduce in my project but no luck yet. Could you please post  which versions of cucumber-junit and pico-container you use? Thanks!

**Comment by mlvandijk** [comment] 2017-09-10 18:41
Cannot reproduce; I've explicitly tried also on Windows 10 (in addition to OS X).
I've created a small project based on information provided(https://github.com/mlvandijk/aritymismatch/blob/master/README.md), but the created test passes both on OS X and Windows...

**Comment by mlvandijk** [comment] 2017-09-11 04:35
Closing this issue as Cannot reproduce. If you can provide steps to reproduce, feel free to Reopen.

**Closed by mlvandijk** 2017-09-11 04:35 UTC
