### ISSUE TITLE
.getSourceTagNames() does not give tags of Examples/Scenarios table

### ISSUE THREAD

**Issue by gkushang** [cucumber/cucumber-jvm#686] opened 2014-03-18 03:05 UTC
scenario.getSourceTagNames() does not return tags on Exampls or Scenarios table,

When I execute @valid_add then it only gives me @add_tests (Tag of Scenario Outline but not Tag of Examples Table) and same is true for @in_valid_add. 

If I am able to run Cukes with Examples table tags then getSourceTagNames() should return the tag names too

@add_tests
  Scenario Outline: Add operation

```
Given I have "<x>" and "<y>"
When I perform add
Then I get "<x+y>"
```

  @valid_add
  Examples:
    | x  | y  | x+y |
    | 2  | 3  | 5   |
    | 1  | 45 | 46  |
    | -3 | 7  | 4   |

  @in_valid_add
  Examples:
    | x  | y  | x+y |
    | 3  | 3  | 8   |
    | 5  | 45 | 36  |
    | -6 | 7  | 2   |

**Comment by brasmusson** [comment] 2017-07-22 19:18
Duplicate of #849.

**Closed by brasmusson** 2017-07-22 19:18 UTC
