### ISSUE TITLE
Java 8 and IllegalArgumentException: Wrong type at constant pool index

### ISSUE THREAD

**Issue by sergey-vladimirovich** [cucumber/cucumber-jvm#998] opened 2016-04-29 11:47 UTC
Hello, there were some troubles with cucumber-jvm running on OpenJDK earlier (see https://github.com/cucumber/cucumber-jvm/issues/912). But it does not work on Oracle JVM too. And it is showstopper, you know.
Somewhere between 1.8.0_51 and 1.8.0_60  Java become cucumber breaker. See https://groups.google.com/forum/#!topic/cukes/VMpJPa1xx58 

I faced this issue when upgraded my Oracle Java 1.8.0_45 to 1.8.0_92.

How to reproduce the issue:
1. Check out this test - https://github.com/mawis/cucumber-java8-test (just created for this long-playing issue)
2. Run 'mvn test'
3. Look at the logs

Expected result: BUILD SUCCESS

Actual result: BUILD FAILURE with the following line as the cause:
Caused by: java.lang.IllegalArgumentException: Wrong type at constant pool index

Environment: Win 10 1511, Oracle JDK 1.8.0_92

This issue is at least critical because it makes cucumber-java8 absolutely unusable. And it is very sad :(

**Comment by RichardBradley** [comment] 2016-05-03 13:13
This is just a duplicate of #912, isn't it?

**Comment by aslakhellesoy** [comment] 2016-08-30 21:14
Yep, dupe of #912

**Closed by aslakhellesoy** 2016-08-30 21:14 UTC
Labels: Bug, Fix in 1.3, Java 8
