### ISSUE TITLE
Cucumber reports - Multi Features

### ISSUE THREAD

**Issue by tiaguiar** [cucumber/cucumber-jvm#951] opened 2016-01-19 12:34 UTC
Hi,

I have an internally mounted test environment without using a CI tool like Jenkins and travis where I schedule my tests.

i use: selenium-grid + maven + cucumber-jvm + junit + cucumber reports plugin

my problem is when I send run a multiple tests (parallel) the cucumber reports plugin only show me the report of the last test .

I need that cucumber reports plugin return me a report with the results of all the tests that were run .

i run my test by command line with maven like this:

<b>mvn clean install -Dtest="teste1, teste2, teste3" -Dcucumber.options="--tags $tags --plugin html:/reports/report --plugin json:/reports/report/output.json" -Dbase.url="$baseurl" -Dnode.url="$nodeurl"</b>

NOTE: if i run only one test, runs fine and the report is perfect.
 

it is possible?  any suggestions to overcome my problem?

**Comment by tommywo** [comment] 2016-01-27 14:26
Each 'RunCukesTest' should have different filename - would be best to set it by @CucumberOptions annotation in class.

**Comment by haroon-sheikh** [comment] 2016-04-16 14:36
@tiaguiar is this still an issue?

**Comment by aslakhellesoy** [comment] 2016-08-30 21:44
Sounds like a dupe of #966

**Closed by aslakhellesoy** 2016-08-30 21:44 UTC
