### ISSUE TITLE
getSourceTagNames() gives back the scenario outline's tags only

### ISSUE THREAD

**Issue by zsolthorvath** [cucumber/cucumber-jvm#648] opened 2013-12-15 13:03 UTC
I'm trying to get all the tags of a scenario which looks like this:

@my_scenario_tag
Scenario Outline: My test scenario
  Given...

```
@my_example_tag
Examples:
  |x|y|
  |u|v|
```

As I understand, the scenario is built up from the combination of the scenario outline and the example table in this case.
But when the getSourceTagNames() method of a scenario object is called (e.g. in a before hook), I'm getting back the @my_scenario_tag only, and the @my_example_tag tag is missing.

**Comment by AlisonOatley** [comment] 2015-08-11 19:53
Has this bug been looked at? It does not seem to be resolved.  I am not seeing the tags above my examples.

**Comment by dkowis** [comment] 2015-08-12 01:43
Pull requests happily accepted!

**Comment by sukeshjain** [comment] 2016-02-23 11:19
Method examples of FilterFormatter class in Gherkin2 project has been changed to fix this problem. However, new version of Gherkin2 is not released. Can we have a new version of Gherkin2 to solve this issue?

**Comment by brasmusson** [comment] 2017-07-22 19:17
Duplicate of #849.

**Closed by brasmusson** 2017-07-22 19:17 UTC
