### ISSUE TITLE
Test failures due to CRLF and Symlink in cucumber-jvm installation tests when running in windows

### ISSUE THREAD

**Issue by jdpennell** [cucumber/cucumber-jvm#2104] opened 2020-08-26 17:35 UTC
**Describe the bug**
When building in Windows using jdk 11.0.2, several tests in BannerTest, CommandLineOptionsParserTest, NoPublishFormatterTest, ResourceScannerTest, and UrlReporterTest fail due to CRLF (carriage return line feed) issues and symlink issues. Maven was launched from git bash.

[BannerTest.results.txt](https://github.com/cucumber/cucumber-jvm/files/5131377/BannerTest.results.txt)
[CommandLineOptionsParserTest.results.txt](https://github.com/cucumber/cucumber-jvm/files/5131378/CommandLineOptionsParserTest.results.txt)
[NoPublishFormatterTest.results.txt](https://github.com/cucumber/cucumber-jvm/files/5131379/NoPublishFormatterTest.results.txt)
[ResourceScannerTest.results.txt](https://github.com/cucumber/cucumber-jvm/files/5131380/ResourceScannerTest.results.txt)
[UrlReporterTest.results.txt](https://github.com/cucumber/cucumber-jvm/files/5131381/UrlReporterTest.results.txt)

**To Reproduce**
1. Add the JDK 11 toolchain to Maven
2. Clone cucumber-jvm to a local disk with no UNC paths
3. In a Git Bash terminal, cd to the cucumber-jvm repository
4. Run either GnuWin32 Make or mvn clean install

**Expected behavior**
The Core project builds without errors, or with errors unrelated to CRLF/LF differences between operating environments
The Core project builds without errors, or with errors unrelated to symlinks not being reported, unless symlink availability is the behavior under test. If performance with symlinks is under test, this test should be skipped if the OS does not support symlinks.

**Context & Motivation**

As an automated test engineer, I would like to be able to build and deploy cucumber to a managed workstation with an unpredictable environment, and I would like test result failures to not exhibit false positives so that important issues can be revealed by included tests.

**Your Environment**
 - commit 26d1ad7fa0a68136461e8d339ce82ff9a7b44f5f
 - Operating system : Windows 10
 - Build tool : Apache Maven 3.6.0

**Comment by mpkorstanje** [comment] 2020-08-26 22:40
> As an automated test engineer, I would like to be able to build and deploy cucumber to a managed workstation with an unpredictable environment, and I would like test result failures to not exhibit false positives so that important issues can be revealed by included tests.

Typically you'd use the artefacts uploaded to Maven Central. Any reason you're building your Cucumber locally?

**Comment by kgeilmann** [comment] 2020-10-05 16:44
Hello, 

May I work on this?

**Comment by mpkorstanje** [comment] 2020-10-05 18:31
Sure! To make things a bit more manageable please submit one PR per class of problem. So one for the platform specific line endings and one for the symlinks.

**Comment by kgeilmann** [comment] 2020-10-05 20:20
Looking into it and as usual the first question is not far away.

Which java version should the source be? Is it ok to use methods available in Java 10+ in Tests? I'm confused, because `mvn install` does not complain if I do, but I see there is a `base.java.version` of 1.8 set in the toplevel pom.xml.

**Comment by mpkorstanje** [comment] 2020-10-05 21:03
Souc

**Comment by mpkorstanje** [comment] 2020-10-05 21:06
Source dfffffffffffffffff

**Comment by mpkorstanje** [comment] 2020-10-05 21:08
The minimum supported jdk is still 8. However the jdk needed to build is 11.

**Comment by kgeilmann** [comment] 2020-10-06 16:25
For the symlinks:

I was able to reproduce it, and to successfully fix it, but it is more a windows + git issue than a coding issue.
In order to make it work, one has to enable symlinks in git before cloning and put windows into developer mode (see [stackoverflow](https://stackoverflow.com/a/59761201)), then it works out of the box. I tried to create the symlink programatically, to at least remove the dependency on the git part, but it keeps telling me, that I don't have the rights to do so.

So I would propose, to either disable the test on windows using `@DisabledOnOs(value = `OS.WINDOWS)` or to add some notes about building on windows to CONTRIBUTING.md.
Any preferred solution?

**Comment by mpkorstanje** [comment] 2020-10-06 16:39
Disabling is probably the least complicated.

**Comment by kgeilmann** [comment] 2020-10-06 22:40
The core module builds now, but it still does not build on windows. 
At least one more test in module cucumber-compatibility fails with a message looking like a similar problem

**Comment by kgeilmann** [comment] 2020-10-12 15:46
#2148 being merged, main branch builds out of the box on windows. I think , this issue can be closed.

**Closed** 2020-10-12 16:57 UTC
Labels: Good First Issue, Hacktoberfest, Help Wanted, platform: windows, type: feature
