### ISSUE TITLE
formatters: JSON formatter cannot express that scenarios failed in an After hook

### ISSUE THREAD

**Issue by anonym** [cucumber/cucumber-jvm#1674] opened 2019-06-06 13:13 UTC
## Summary
I've seen [indications](https://github.com/cucumber/cucumber-jvm/issues/901) that failing a scenario from an `After` hook is supposed to be supported. If this is not the case then this issue is invalid and should be rejected.

In a project I am involved with we found great use for this: in most of our scenarios we want to make sure that only certain hosts are connected to, so we start `tcpdump` in a `Before` hook and check if any illegal hosts were contacted in the `After` hook. This way we don't need two explicit steps for this in most scenarios, which helps readability.

This works great, except for the JSON formatter, which only records status for steps, and lacks a way to express that a scenario failed outside of a step, e.g. in an `After` hook.

This might be something to fix while you work on #415 (?)

## Expected Behavior
The JSON formatter should be able to express when a scenario was failed outside of a step, e.g. in an `After` hook.

## Current Behavior
The current JSON formatter only records step status, not status for the whole scenario, so it cannot express when a scenario fails in an `After` hook.

## Possible Solution
For instance, adding a status field for each scenario.

## Steps to Reproduce (for bugs)
My project is way too convoluted to give a clear example from so I'll just describe a simple reproducer:

1. Create a minimal scenario that always passes
2. Add an `After` hook that fails the scenario (e.g. throw an exception)
3. Run with both the default and JSON formatters
4. Notice how cucumber itself (and the default formatter) handles the failure perfectly, but there is no trace of the failure in the JSON log.

## Context & Motivation
In our CI, Jenkins has a cucumber plugin which consumes the JSON formatter's output. Because of this issue, any scenario that fails in an `After` hook is reported as passing. With a fix for this issue we could in turn update the Jenkins plugin to handle this properly.

**Comment by mpkorstanje** [comment] 2019-06-27 16:20
I can't reproduce this problem using a recent version of `cucumber-jvm`. When a hook fails the hook is properly marked as failed. E.g. adding a failing hook to the [cucumber-java-skeleton](https://github.com/cucumber/cucumber-java-skeleton):

```java
    @After
    public void fail(){
        throw new IllegalStateException();
    }
```

Results in:

```
[
  {
    "line": 1,
    "elements": [
      {
        "start_timestamp": "2019-06-27T16:15:16.520Z",
        "line": 3,
        "name": "a few cukes",
        "description": "",
        "id": "belly;a-few-cukes",
        "after": [
          {
            "result": {
              "error_message": "java.lang.IllegalStateException\n\tat io.cucumber.skeleton.Stepdefs.fail(Stepdefs.java:15)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat cucumber.runtime.Utils$1.call(Utils.java:26)\n\tat cucumber.runtime.Timeout.timeout(Timeout.java:16)\n\tat cucumber.runtime.Utils.invoke(Utils.java:20)\n\tat cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)\n\tat cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)\n\tat cucumber.runner.TestStep.executeStep(TestStep.java:65)\n\tat cucumber.runner.TestStep.run(TestStep.java:50)\n\tat cucumber.runner.TestCase.run(TestCase.java:50)\n\tat cucumber.runner.Runner.runPickle(Runner.java:49)\n\tat cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:123)\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:65)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat cucumber.api.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:147)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.junit.runner.JUnitCore.run(JUnitCore.java:137)\n\tat com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)\n\tat com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)\n\tat com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)\n\tat com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)\n",
              "duration": 336615,
              "status": "failed"
            },
            "match": {
              "location": "Stepdefs.fail()"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 541426,
              "status": "passed"
            },
            "line": 4,
            "name": "I have 42 cukes in my belly",
            "match": {
              "arguments": [
                {
                  "val": "42",
                  "offset": 7
                }
              ],
              "location": "Stepdefs.I_have_cukes_in_my_belly(int)"
            },
            "keyword": "Given "
          }
        ]
      }
    ],
    "name": "Belly",
    "description": "",
    "id": "belly",
    "keyword": "Feature",
    "uri": "classpath:io/cucumber/skeleton/belly.feature",
    "tags": []
  }
]
```

**Closed by mpkorstanje** 2019-06-27 16:20 UTC

**Comment by mpkorstanje** [comment] 2019-06-27 16:22
If you can provide a reproducer using a recent version of `cucumber-jvm` please feel free to reopen. If you can provide a reproducer please do so in the form of a github project.

**Comment by anonym** [comment] 2019-06-28 09:46
Crap, I posted this in the wrong place. I am having this issue with @cucumber-ruby@, so I'll repost there. I am so very sorry for wasting your time!

**Comment by mpkorstanje** [comment] 2019-06-28 11:40
LOL. No worries!
