### ISSUE TITLE
html plugin - missing embeddings in case of scenario with multiple examples

### ISSUE THREAD

**Issue by kennebnonedz** [cucumber/cucumber-jvm#2158] opened 2020-10-22 13:16 UTC
Hi,

I recently tried to migrate my web testing project to cucumber-jvm-6.7.0
I use the HTML plugin to generate reports. A good practice is to capture a screenshot on test failure.
The embedded resource is visible correctly in case of a _Scenario_ or _Scenario Outline_ with only one example, it is not if the _Scenario Outline_ has more than one example.

The embedded resources work correctly in the JSON report.

BR,
kennebnonedz

**Environment**
 - Versions used 6.7.0
 - OS: Windows, Linux
 - Build tool: Apache Maven 3.6.3

**Comment by aslakhellesoy** [comment] 2020-10-22 13:24
Duplicate of https://github.com/cucumber/cucumber/issues/1173

**Closed by aslakhellesoy** 2020-10-22 13:24 UTC
