### ISSUE TITLE
CLI doesn't handle exceptions very well

### ISSUE THREAD

**Issue by smmckay** [cucumber/cucumber-jvm#831] opened 2015-01-28 19:27 UTC
I'm using cucumber-spring with the CLI, and under certain conditions Spring can throw an exception that percolates up through `cucumber.api.cli.Main.main()` and aborts the runner. This _doesn't_ exit the process because of non-daemon threads started by libraries.

The workaround I'm using is to install a default uncaught exception handler that calls `System.exit(1)`.

I'm not sure if this is a bug in the CLI or the Java backend.

**Comment by paoloambrosio** [comment] 2015-02-02 07:37
What kind of exceptions are causing this behaviour?

I guess what you say about non-daemon threads is because the Spring context is not torn down, so it doesn't call the destroy methods you have defined for the beans. Am I correct?

**Comment by aslakhellesoy** [comment] 2015-02-02 08:33
Please provide a way to reproduce this, without which we can't fix this. Or better yet - a pull request with a fix (and a test).

**Comment by mathan91** [comment] 2017-06-07 08:08
I'm getting the same issue. Posted in stackoverflow as well, 
https://stackoverflow.com/questions/44307006/the-cucumber-cli-stops-without-any-error

Below is the code,
@Test
public void runTest() throws Throwable {
` try {
        String[] getRequest = GetRequest.testValuesReturn();
        Main.main(new String[]{"-g", "com.sanity.step.definition","-t", "@" +getRequest[1], 
        "C:/Users/IBM_ADMIN/Documents/Automation/Performance 
        Testing/PerformanceTesting/MyFeature.feature"});
        System.out.println("Print");
    } catch (Exception e) {
        e.printStackTrace();
    }
}   ` 
The feature file 
`When Start the performance Test
 When Open the Inventory Page
 When Click on Seamless Switch`

The last annotated method is 
`@When("^Click on Seamless Switch$")
    public void Seamless_Switch() throws Throwable {    
    driver.baseDriver.findElement(By.id("seamlessSwitchButton")).click();
    log.info("Seamless switch is clicked");
    System.out.println("Click on Seamless Switch");
}`

It's printing until "Click on Seamless Switch". But the syso in @Test annotated method ("Print") is not printed in the console.
Why is it stopping without any exception? Because of this issue, in JMeter, I'm getting the following errors before even completion of the thread,
`2017/06/01 13:40:31 INFO  - jmeter.reporters.ResultCollector: Shutdown hook started 
 2017/06/01 13:40:31 INFO  - jmeter.reporters.ResultCollector: Shutdown hook ended  `

**Comment by mpkorstanje** [comment] 2017-10-11 19:24
Closing this issue due to age. Feel free to reopen if a way to reproduce can be found.

**Closed by mpkorstanje** 2017-10-11 19:24 UTC
Labels: Bug, Need Pull Request, Spring
